const SUPABASE_URL='https://basfrphvvjfhbozxaeyw.supabase.co';
const SUPABASE_KEY='sb_publishable_tceA1IKdfumh9-HvFCpp1g_m0zCmu72';
const sb=supabase.createClient(SUPABASE_URL,SUPABASE_KEY);
const loginCard=document.querySelector('#loginCard'),dashboard=document.querySelector('#dashboard'),orders=document.querySelector('#orders');
const labels={new:'Novo',contacted:'Em contato',quote_sent:'Orçamento enviado',closed:'Fechado',paid:'Pago',lost:'Não fechou'};
const money=v=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(Number(v||0));
const date=v=>new Intl.DateTimeFormat('pt-BR',{dateStyle:'short',timeStyle:'short'}).format(new Date(v));
function show(auth){loginCard.hidden=auth;dashboard.hidden=!auth;if(auth)loadOrders()}
document.querySelector('#loginForm').addEventListener('submit',async e=>{e.preventDefault();const msg=document.querySelector('#loginMsg');msg.textContent='Entrando...';const {error}=await sb.auth.signInWithPassword({email:document.querySelector('#email').value,password:document.querySelector('#password').value});msg.textContent=error?'E-mail ou senha inválidos.':''});
document.querySelector('#logout').onclick=()=>sb.auth.signOut();
sb.auth.onAuthStateChange((_e,s)=>show(!!s));
sb.auth.getSession().then(({data})=>show(!!data.session));
async function loadOrders(){const msg=document.querySelector('#dashMsg');msg.textContent='Carregando...';const {data,error}=await sb.from('quote_requests').select('id,created_at,name,email,service,message,status,sale_value').order('created_at',{ascending:false});if(error){msg.textContent='Não foi possível carregar os pedidos.';return}msg.textContent='';render(data||[])}
function render(data){document.querySelector('#total').textContent=data.length;const p=data.filter(x=>x.status==='paid');document.querySelector('#paid').textContent=p.length;document.querySelector('#revenue').textContent=money(p.reduce((s,x)=>s+Number(x.sale_value||0),0));orders.innerHTML=data.length?'':'<div class="card">Nenhum pedido encontrado.</div>';data.forEach(x=>{const el=document.createElement('article');el.className='order';el.innerHTML='<div class="top"><div><strong></strong><div class="service"></div><div class="muted meta"></div></div><div class="muted dt"></div></div><p class="message"></p><div class="controls"><select></select><input type="number" min="0" step="0.01" placeholder="Valor R$"><button>Salvar</button></div>';el.querySelector('strong').textContent=x.name;el.querySelector('.service').textContent=x.service;el.querySelector('.meta').textContent=x.email;el.querySelector('.dt').textContent=date(x.created_at);el.querySelector('.message').textContent=x.message||'Sem mensagem.';const sel=el.querySelector('select');Object.entries(labels).forEach(([v,l])=>sel.add(new Option(l,v)));sel.value=x.status;const inp=el.querySelector('input');inp.value=x.sale_value??'';el.querySelector('button').onclick=()=>save(x.id,sel.value,inp.value,el.querySelector('button'));orders.appendChild(el)})}
async function save(id,status,value,btn){btn.disabled=true;btn.textContent='Salvando...';const sale_value=value===''?null:Number(value);const {error}=await sb.from('quote_requests').update({status,sale_value}).eq('id',id);btn.disabled=false;btn.textContent=error?'Erro':'Salvo';if(!error)setTimeout(loadOrders,500);else setTimeout(()=>btn.textContent='Salvar',1500)}
